image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:      #内参,单位是 像素/m
  rows: 3
  cols: 3
  # data: [732.60558,   0.     , 179.39814,
  #          0.     , 702.61351, 231.89372,
  #          0.     ,   0.     ,   1.     ] 
  data: [732.60558,   0.     , 320,
          0.     , 702.61351, 240,
          0.     ,   0.     ,   1.     ] 
           #相机坐标系转世界坐标系矩阵A，[x,y,c,1](world) = A * [x,y,z,1](camera)
distortion_model: plumb_bob
distortion_coefficients:  #径向畸变和切向畸变
  rows: 1
  cols: 5
  data: [0.199984, -0.000136, -0.015266, -0.087766, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]                      #像素坐标系转图像坐标系矩阵B [u,v,1] = B * [x,y,1]
projection_matrix:
  rows: 3
  cols: 4
  data: [716.28448,   0.     , 154.946  ,   0.     ,
           0.     , 747.97284, 228.09873,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]  #世界坐标系转像素坐标系矩阵C [x,y,1] = C * [x,y,z,1]

#世界坐标系转像素坐标系: [u,v,1] = B * C * A * [x,y,z,1]
#B为单位矩阵，暂时忽略   [u,v,1]T = C * A * [x,y,z,1]
#[x,y,z,1]偏置项暂时去掉变为[x,y,z]T
#C矩阵要前三列 [3*3]
#[3*3][3*3][3*1]T  
#ROS坐标系的单位是米/m
#[3*3][3*3] = [0.525, 0.       ,0.129,
#              0.   , 0.5255   ,0.174,
#              0.   , 0.       ,1.]
#        D  = [1.905, 0.       ,-0.2457,
#              0.   , 1.903    ,-0.331,
#              0.   , 0.       ,1.]
#        像素坐标系转世界坐标系
#        D * [u,v,1]T = [x,y,z]T