// Automatically generated
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/AltimeterSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/CameraSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/ContactSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/DepthCameraSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/ForceTorqueSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/GaussianNoiseModel.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/GpsSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/GpuRaySensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/ImuSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/LogicalCameraSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/MagnetometerSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/MultiCameraSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/Noise.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/RaySensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/RFIDSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/RFIDTag.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/SensorsIface.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/Sensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/SensorTypes.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/SensorFactory.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/SensorManager.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/SonarSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/WideAngleCameraSensor.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/WirelessReceiver.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/WirelessTransceiver.hh"
 #include "/home/ubuntu/wtr_upmachine_ws/src/assembly/include/gazebo/sensors/WirelessTransmitter.hh"

