# Topics Advertised
TrajectoryTopic:            '/example0/trajectory'
WayPointsTopic:             '/example0/waypoints'
RouteTopic:                 '/example0/route'
AccTopic:                   '/example0/acc'

# Frame Name
FrameName:                  'world'

# Params
WeightT:                     1024.0

WeightAcc:                   16.0

WeightJerk:                  0.4

MaxAccRate:                  1.50

MaxVelRate:                  0.80

Iterations:                  23

Epsilon:                     0.02

##process1
# Number of Points 
PointNumber:                   3

#process2
#Different Number of Points in every part .cpp文件中maxPointParts设置20,最多区间小于20即可
PointArray:                   [3,3,4,4]
#Maximum segment  此值小于等于PointArray元素个数即可
MaxParts:                       3

#process3
#The point coordinates to be passed in
                             #x       #y      #z
PointSet:                 [ 0.0,      0.0,    0.0,           
                            1,      2,      3,            
                            2,      3,      4,
                            3,      4,      5,
                            4,      5,      6]           
MaxPointSetNumber:              15         #3*3,PointSet元素个数，即坐标点数*3

#process4
#Set the coordinate points of multiple segments
                             #x       #y      #z
PointSet_:                 [ 0.0,      0.0,    0.0,           
                            1,      2,      3,            
                            2,      3,      4,

                            3,      4,      5,
                            4,      5,      6,
                            5,      6,      7,
                            
                            6,      7,      8,
                            7,      8,      9,
                            8,      9,      10,
                            9,      10,     11,

                            10,     11,     12,
                            11,     12,     13,
                            12,     13,     14,
                            13,     14,     15
                            ]   
MaxPointSetNumber_:              42       #上面一维数组元素总数
PointArray_:                 [3,3,4,4]    #每个区段的点数(能力有限，应与坐标元素数组间隔一一对应)
MaxParts_:                       2        #此值小于等于PointArray_元素个数即可